# NEJEN boot splash: install the nejen Plymouth theme, make it the default,
# ensure the initramfs runs the plymouth hook, and rebuild the boot image
# (a plain initramfs, or a UKI on Limine machines).
#
# Idempotent, safe to re-run. Never edits /etc/mkinitcpio.conf itself:
# NEJEN owns exactly one drop-in (/etc/mkinitcpio.conf.d/nejen-plymouth.conf)
# that restates the effective HOOKS with plymouth inserted. Any leftover
# legacy hooks drop-in is absorbed into ours and retired (renamed *.bak so
# mkinitcpio no longer reads it) -- its hook list is preserved, so encrypted
# roots keep booting.
#
# Runs standalone on an existing machine too:
#   NEJEN_PATH=~/.local/share/nejen bash install/first-run/boot-theme.sh

set -euo pipefail

# Normally inherited from the dispatcher. Standalone runs resolve the same way
# it does: dev-mode tree first, then the packaged location.
if [ -z "${NEJEN_PATH:-}" ]; then
  if [ -d "$HOME/.local/share/nejen" ]; then
    NEJEN_PATH="$HOME/.local/share/nejen"
  else
    NEJEN_PATH=/usr/share/nejen
  fi
fi
THEME_SRC="$NEJEN_PATH/config/plymouth/nejen"
THEME_DST=/usr/share/plymouth/themes/nejen
PLYMOUTHD_CONF=/etc/plymouth/plymouthd.conf
DROPIN=/etc/mkinitcpio.conf.d/nejen-plymouth.conf
GEN_MARK="Generated by NEJEN"

if ! command -v plymouth-set-default-theme >/dev/null; then
  echo "plymouth is not installed; skipping boot splash setup" >&2
  exit 0
fi

# --- 1. Theme files ----------------------------------------------------------
# The nejen package ships them pacman-owned at $THEME_DST; in dev mode we
# copy from the checkout (and never clobber a pacman-owned install).
if ! pacman -Qo "$THEME_DST/nejen.plymouth" &>/dev/null; then
  echo "Installing Plymouth theme to $THEME_DST"
  sudo mkdir -p "$THEME_DST"
  sudo cp -f "$THEME_SRC"/* "$THEME_DST"/
fi

# --- 2. Default theme ---------------------------------------------------------
# ShowDelay=0 so the splash owns the screen immediately (also the LUKS prompt).
if ! sudo grep -qs "$GEN_MARK" "$PLYMOUTHD_CONF"; then
  if [[ -e $PLYMOUTHD_CONF ]]; then
    sudo mv "$PLYMOUTHD_CONF" "$PLYMOUTHD_CONF.pre-nejen.bak"
    echo "Backed up existing plymouthd.conf to $PLYMOUTHD_CONF.pre-nejen.bak"
  fi
fi
sudo tee "$PLYMOUTHD_CONF" >/dev/null <<EOF
# $GEN_MARK (install/first-run/boot-theme.sh) -- edits will be overwritten.
[Daemon]
Theme=nejen
ShowDelay=0
EOF

# --- 3. plymouth hook in the initramfs ----------------------------------------
# Reproduce mkinitcpio's own config resolution: the main conf, then conf.d
# drop-ins in lexical order, last HOOKS assignment wins.
effective_hooks=""
for conf in /etc/mkinitcpio.conf /etc/mkinitcpio.conf.d/*.conf; do
  [[ -f $conf ]] || continue
  hooks="$(bash -c 'source "$1" >/dev/null 2>&1; echo "${HOOKS[*]:-}"' _ "$conf")"
  [[ -n $hooks ]] && effective_hooks="$hooks"
done

if [[ -z $effective_hooks ]]; then
  echo "Could not determine mkinitcpio HOOKS; not touching the initramfs" >&2
  exit 1
fi

# Insert plymouth right after the init framework hook (systemd or udev).
if [[ " $effective_hooks " != *" plymouth "* ]]; then
  for anchor in systemd udev base; do
    if [[ " $effective_hooks " == *" $anchor "* ]]; then
      effective_hooks="${effective_hooks/$anchor/$anchor plymouth}"
      break
    fi
  done
fi

sudo tee "$DROPIN" >/dev/null <<EOF
# $GEN_MARK (install/first-run/boot-theme.sh) -- edits will be overwritten.
# Restates the machine's effective HOOKS with plymouth added; regenerate by
# re-running the script after changing /etc/mkinitcpio.conf.
HOOKS=($effective_hooks)
EOF

# Retire foreign drop-ins that set HOOKS so NEJEN's drop-in takes precedence.
for conf in /etc/mkinitcpio.conf.d/*.conf; do
  [[ -f $conf && $conf != "$DROPIN" ]] || continue
  grep -qE '^[[:space:]]*HOOKS' "$conf" || continue
  if [[ ${conf##*/} != *nejen* ]]; then
    sudo mv "$conf" "$conf.pre-nejen.bak"
    echo "Retired foreign drop-in $conf (hooks absorbed into $DROPIN)"
  fi
done

# --- 4. Activate ----------------------------------------------------------------
if ! grep -qw splash /proc/cmdline; then
  echo "NOTE: kernel cmdline has no 'splash' flag; add it in your bootloader" \
    "entry or the splash will stay hidden." >&2
fi

# The splash lives inside the boot image, so nothing changes on screen until that
# image is rebuilt -- and the command to rebuild it is not the same everywhere.
#
# On a Limine/UKI machine (limine-mkinitcpio-hook) /etc/mkinitcpio.d is empty and
# /usr/local/bin/mkinitcpio shadows the real binary with a wrapper that builds
# nothing, prints a warning, and then INTERACTIVELY offers to run
# limine-mkinitcpio. `mkinitcpio -P` there is a no-op whenever nobody is at the
# keyboard to answer -- an unattended install, or the Stage 2 installer. So
# dispatch explicitly, and fail loudly rather than leave a stale boot image
# behind a zero exit code.
echo "Rebuilding the boot image with the nejen splash"

shopt -s nullglob
presets=(/etc/mkinitcpio.d/*.preset)
shopt -u nullglob

if command -v limine-mkinitcpio >/dev/null; then
  sudo limine-mkinitcpio
elif (( ${#presets[@]} )); then
  # Absolute path on purpose: the real binary, never whatever shadows it.
  sudo /usr/bin/mkinitcpio -P
else
  echo "ERROR: this machine has no mkinitcpio presets and no limine-mkinitcpio," \
    "so the boot image was NOT rebuilt. The theme is installed, but the splash" \
    "will not change until you regenerate the initramfs or UKI yourself." >&2
  exit 1
fi
