package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func init() {
	registerCommand("install", runInstall)
	registerCommand("install deps", runInstallDeps)
}

func installLog(format string, a ...interface{}) {
	fmt.Printf("\033[32m==>\033[0m "+format+"\n", a...)
}

func installWarn(format string, a ...interface{}) {
	fmt.Printf("\033[33m==>\033[0m "+format+"\n", a...)
}

// backupForeign moves aside a file NEJEN did not generate, so the caller can
// write in its place. It reports an error rather than returning silently when
// the move fails: callers overwrite the target immediately afterwards, so a
// swallowed failure destroys the very file this is meant to preserve.
func backupForeign(target string) error {
	info, err := os.Lstat(target)
	if err != nil {
		return nil // does not exist
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return nil // symlink
	}

	if !info.IsDir() {
		b, err := os.ReadFile(target)
		if err == nil && strings.Contains(string(b), genMark) {
			return nil
		}
	}

	backup := backupNameFor(target)
	if err := os.Rename(target, backup); err != nil {
		return fmt.Errorf("could not back up %s: %w", target, err)
	}

	home, _ := os.UserHomeDir()
	shorten := func(p string) string { return strings.Replace(p, home, "~", 1) }
	installWarn("Backed up existing %s to %s", shorten(target), shorten(backup))
	return nil
}

// backupNameFor never reuses an existing backup path. The first .pre-nejen.bak
// holds the configuration from before NEJEN was installed at all -- the one
// copy that cannot be regenerated -- so a second install finding another
// foreign file gets a numbered name instead of overwriting it.
func backupNameFor(target string) string {
	backup := target + ".pre-nejen.bak"
	if _, err := os.Lstat(backup); err != nil {
		return backup
	}
	for i := 2; i < 1000; i++ {
		candidate := fmt.Sprintf("%s.pre-nejen.%d.bak", target, i)
		if _, err := os.Lstat(candidate); err != nil {
			return candidate
		}
	}
	return backup
}

const genMark = "Generated by NEJEN install.sh"

func writeGen(target, content string) {
	if info, err := os.Lstat(target); err == nil && info.Mode()&os.ModeSymlink != 0 {
		os.Remove(target)
	}
	if err := backupForeign(target); err != nil {
		installWarn("%v - leaving your file in place", err)
		return
	}

	if b, err := os.ReadFile(target); err != nil || string(b) != content {
		if err := os.WriteFile(target, []byte(content), 0644); err != nil {
			installWarn("could not write %s: %v", target, err)
		}
	}
}

func ensureOverride(target, content string) {
	if _, err := os.Stat(target); err == nil {
		return
	}
	os.WriteFile(target, []byte(content), 0644)
}

func linkTo(src, target string) {
	if err := backupForeign(target); err != nil {
		installWarn("%v - leaving your file in place", err)
		return
	}
	os.Remove(target)
	if err := os.Symlink(src, target); err != nil {
		installWarn("could not link %s: %v", target, err)
	}
}

func runInstallDeps(args []string) {
	manifest := "full"
	if len(args) > 0 {
		manifest = args[0]
	}

	home, _ := os.UserHomeDir()
	nejenPath := filepath.Join(home, ".local", "share", "nejen")
	pkgFile := filepath.Join(nejenPath, "packages", manifest+".txt")

	b, err := os.ReadFile(pkgFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to read %s: %v\n", pkgFile, err)
		return
	}

	var official []string
	var aur []string
	section := ""

	lines := strings.Split(string(b), "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "## Official repos") {
			section = "official"
			continue
		} else if strings.HasPrefix(trimmed, "## AUR") {
			section = "aur"
			continue
		}

		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		if section == "official" {
			official = append(official, trimmed)
		} else if section == "aur" {
			aur = append(aur, trimmed)
		}
	}

	if len(official) > 0 {
		installLog("Installing %d official-repo packages (%s manifest)...", len(official), manifest)
		pacmanArgs := append([]string{"-S", "--needed", "--noconfirm"}, official...)
		cmd := exec.Command("sudo", append([]string{"pacman"}, pacmanArgs...)...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		cmd.Stdin = os.Stdin
		if err := cmd.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "pacman failed: %v\n", err)
		}
	}

	if len(aur) > 0 {
		if os.Geteuid() == 0 {
			installWarn("Running as root - skipping %d AUR packages (AUR helpers refuse to build as root).", len(aur))
			installWarn("Run install.sh again as a normal user to pick those up, or pre-bake them into the ISO.")
			return
		}

		var aurHelper string
		if _, err := exec.LookPath("paru"); err == nil {
			aurHelper = "paru"
		} else if _, err := exec.LookPath("yay"); err == nil {
			aurHelper = "yay"
		} else {
			installWarn("No AUR helper (paru/yay) found - skipping %d AUR packages.", len(aur))
			return
		}

		installLog("Installing %d AUR packages via %s...", len(aur), aurHelper)
		aurArgs := append([]string{"-S", "--needed", "--noconfirm"}, aur...)
		cmd := exec.Command(aurHelper, aurArgs...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		cmd.Stdin = os.Stdin
		if err := cmd.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "%s failed: %v\n", aurHelper, err)
		}
	}
}

func runInstall(args []string) {
	packages := true
	manifest := "full"
	expectManifest := false

	for _, arg := range args {
		if expectManifest {
			manifest = arg
			expectManifest = false
			continue
		}
		switch {
		case arg == "--no-packages" || arg == "--skip-packages":
			packages = false
		case arg == "--packages":
			expectManifest = true
		case strings.HasPrefix(arg, "--packages="):
			manifest = strings.TrimPrefix(arg, "--packages=")
		default:
			fmt.Fprintln(os.Stderr, "usage: install.sh [--no-packages] [--packages core|full]")
			os.Exit(2)
		}
	}

	if manifest != "core" && manifest != "full" {
		fmt.Fprintf(os.Stderr, "install.sh: --packages must be 'core' or 'full' (got '%s')\n", manifest)
		os.Exit(2)
	}

	sourcePath := os.Getenv("NEJEN_SOURCE_PATH")
	if sourcePath == "" {
		sourcePath, _ = os.Getwd()
	}
	home, _ := os.UserHomeDir()
	nejenPath := filepath.Join(home, ".local", "share", "nejen")
	configDir := filepath.Join(home, ".config")

	stateDir := os.Getenv("XDG_STATE_HOME")
	if stateDir == "" {
		stateDir = filepath.Join(home, ".local", "state")
	}
	stateDir = filepath.Join(stateDir, "nejen")

	// ~/.local/share/nejen is often a symlink straight at a checkout, so
	// compare resolved paths: rsync --delete onto itself would be walking
	// the repo while deleting from it.
	sourceReal, errS := filepath.EvalSymlinks(sourcePath)
	nejenReal, errN := filepath.EvalSymlinks(nejenPath)
	sameTree := errS == nil && errN == nil && sourceReal == nejenReal

	if sameTree {
		installLog("Source tree is already %s - skipping mirror.", nejenPath)
	} else if sourcePath != nejenPath {
		installLog("Mirroring repo to %s...", nejenPath)
		os.MkdirAll(nejenPath, 0755)
		cmd := exec.Command("rsync", "-a", "--delete", sourcePath+"/", nejenPath+"/", "--exclude", "install.sh", "--exclude", "archiso", "--exclude", "build-iso.sh", "--exclude", ".git")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "rsync failed: %v\n", err)
		}
	}

	if packages {
		runInstallDeps([]string{manifest})
	} else {
		installWarn("Skipping package install (--no-packages) - assuming they're already present.")
	}

	if info, err := os.Stat(filepath.Join(nejenPath, "install", "first-run", "pacman-hooks.sh")); err == nil && !info.IsDir() {
		cmd := exec.Command("bash", filepath.Join(nejenPath, "install", "first-run", "pacman-hooks.sh"))
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		cmd.Run()
	}

	installLog("Compiling Go binary to bin/nejen...")
	buildCmd := exec.Command("go", "build", "-o", filepath.Join(nejenPath, "bin", "nejen"), "./cmd/nejen/...")
	buildCmd.Dir = nejenPath
	buildCmd.Stdout = os.Stdout
	buildCmd.Stderr = os.Stderr
	if err := buildCmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "go build failed: %v\n", err)
	}

	installLog("Installing bin/nejen onto PATH (~/.local/bin) and bash completion...")
	os.MkdirAll(filepath.Join(home, ".local", "bin"), 0755)
	linkTo(filepath.Join(nejenPath, "bin", "nejen"), filepath.Join(home, ".local", "bin", "nejen"))
	os.MkdirAll(filepath.Join(home, ".local", "share", "bash-completion", "completions"), 0755)
	linkTo(filepath.Join(nejenPath, "completions", "nejen.bash"), filepath.Join(home, ".local", "share", "bash-completion", "completions", "nejen"))

	installLog("Creating NEJEN config/state dirs...")
	os.MkdirAll(filepath.Join(configDir, "nejen"), 0755)
	os.MkdirAll(stateDir, 0755)

	if info, err := os.Lstat(filepath.Join(configDir, "nejen", "themes")); err == nil && info.Mode()&os.ModeSymlink != 0 {
		os.Remove(filepath.Join(configDir, "nejen", "themes"))
	}
	os.MkdirAll(filepath.Join(configDir, "nejen", "themes"), 0755)

	os.MkdirAll(filepath.Join(configDir, "nejen", "branding"), 0755)
	for _, f := range []string{"about.txt", "screensaver.txt"} {
		target := filepath.Join(configDir, "nejen", "branding", f)
		if info, err := os.Lstat(target); err != nil || info.Mode()&os.ModeSymlink != 0 {
			linkTo(filepath.Join(nejenPath, "logo.txt"), target)
		}
	}

	installLog("Activating default theme (nejen theme set nejen)...")
	cmd := exec.Command(filepath.Join(nejenPath, "bin", "nejen"), "theme", "set", "nejen")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Run()

	installLog("Rendering keymap (nejen keymap render)...")
	cmd = exec.Command(filepath.Join(nejenPath, "bin", "nejen"), "keymap", "render")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Run()

	installLog("Deploying layered config into ~/.config...")
	os.MkdirAll(configDir, 0755)
	for _, name := range []string{"hypr", "alacritty", "waybar", "swayosd", "bluetuith", "btop", "mako"} {
		target := filepath.Join(configDir, name)
		if info, err := os.Lstat(target); err == nil && info.Mode()&os.ModeSymlink != 0 {
			os.Remove(target)
		}
	}

	os.MkdirAll(filepath.Join(configDir, "hypr"), 0755)
	writeGen(filepath.Join(configDir, "hypr", "hyprland.conf"), "# "+genMark+" - DO NOT EDIT, this file is regenerated on install/update.\n# Layered config: NEJEN defaults first, then your overrides (they win).\nsource = $NEJEN_PATH/config/hypr/hyprland.conf\nsource = ~/.config/hypr/overrides.conf")
	ensureOverride(filepath.Join(configDir, "hypr", "overrides.conf"), "# Your personal Hyprland overrides. Sourced last, so anything here wins over\n# the NEJEN defaults. This file is never touched by NEJEN updates.")

	writeGen(filepath.Join(configDir, "hypr", "hyprlock.conf"), "# "+genMark+" - DO NOT EDIT, this file is regenerated on install/update.\nsource = $NEJEN_PATH/config/hypr/hyprlock.conf\nsource = ~/.config/hypr/hyprlock-overrides.conf")
	ensureOverride(filepath.Join(configDir, "hypr", "hyprlock-overrides.conf"), "# Your personal hyprlock overrides. Never touched by NEJEN updates.")

	linkTo(filepath.Join(nejenPath, "config", "hypr", "hypridle.conf"), filepath.Join(configDir, "hypr", "hypridle.conf"))
	linkTo(filepath.Join(nejenPath, "config", "hypr", "hyprsunset.conf"), filepath.Join(configDir, "hypr", "hyprsunset.conf"))
	linkTo(filepath.Join(nejenPath, "config", "hypr", "xdph.conf"), filepath.Join(configDir, "hypr", "xdph.conf"))

	os.MkdirAll(filepath.Join(configDir, "alacritty"), 0755)
	writeGen(filepath.Join(configDir, "alacritty", "alacritty.toml"), "# "+genMark+" - DO NOT EDIT, this file is regenerated on install/update.\n# Layered config: NEJEN defaults first, then your overrides (they win).\ngeneral.import = [\n  \""+nejenPath+"/config/alacritty/alacritty.toml\",\n  \"~/.config/alacritty/overrides.toml\",\n]")
	ensureOverride(filepath.Join(configDir, "alacritty", "overrides.toml"), "# Your personal Alacritty overrides. Imported last, so anything here wins\n# over the NEJEN defaults. Never touched by NEJEN updates.")

	os.MkdirAll(filepath.Join(configDir, "waybar"), 0755)
	wbConfig := filepath.Join(configDir, "waybar", "config.jsonc")
	if info, err := os.Lstat(wbConfig); err != nil || info.Mode()&os.ModeSymlink != 0 {
		linkTo(filepath.Join(nejenPath, "config", "waybar", "config.jsonc"), wbConfig)
	} else {
		installLog("Keeping user-owned waybar/config.jsonc (not a symlink - yours)")
	}
	writeGen(filepath.Join(configDir, "waybar", "style.css"), "/* "+genMark+" - DO NOT EDIT, regenerated on install/update.\n * Layered: rendered theme, NEJEN defaults, then your overrides.css (wins). */\n@import \"../../.local/state/nejen/theme/waybar.css\";\n@import \""+nejenPath+"/config/waybar/style.css\";\n@import \"overrides.css\";")
	ensureOverride(filepath.Join(configDir, "waybar", "overrides.css"), "/* Your personal Waybar styles. Imported last, so they win over the NEJEN\n * defaults. Never touched by NEJEN updates. */")

	os.MkdirAll(filepath.Join(configDir, "swayosd"), 0755)
	linkTo(filepath.Join(nejenPath, "config", "swayosd", "config.toml"), filepath.Join(configDir, "swayosd", "config.toml"))
	writeGen(filepath.Join(configDir, "swayosd", "style.css"), "/* "+genMark+" - DO NOT EDIT, regenerated on install/update.\n * Layered: rendered theme, NEJEN defaults, then your overrides.css (wins). */\n@import \"../../.local/state/nejen/theme/swayosd.css\";\n@import \""+nejenPath+"/config/swayosd/style.css\";\n@import \"overrides.css\";")
	ensureOverride(filepath.Join(configDir, "swayosd", "overrides.css"), "/* Your personal swayosd styles. Imported last, so they win over the NEJEN\n * defaults. Never touched by NEJEN updates. */")

	// bluetuith reads a single HJSON file that carries both its theme and its
	// keybindings, with no include mechanism -- so the whole file is rendered
	// by the theme engine and linked from state, the same way btop's theme is.
	os.MkdirAll(filepath.Join(configDir, "bluetuith"), 0755)
	linkTo(filepath.Join(stateDir, "theme", "bluetuith.conf"), filepath.Join(configDir, "bluetuith", "bluetuith.conf"))

	os.MkdirAll(filepath.Join(configDir, "btop", "themes"), 0755)
	btopConf := filepath.Join(configDir, "btop", "btop.conf")
	if _, err := os.Stat(btopConf); err != nil {
		if b, err := os.ReadFile(filepath.Join(nejenPath, "config", "btop", "btop.conf")); err == nil {
			os.WriteFile(btopConf, b, 0644)
		}
	}
	linkTo(filepath.Join(stateDir, "theme", "btop.theme"), filepath.Join(configDir, "btop", "themes", "current.theme"))

	os.MkdirAll(filepath.Join(configDir, "mako"), 0755)
	ensureOverride(filepath.Join(configDir, "nejen", "mako-overrides"), "# Your personal mako GLOBAL options (colors, font, timeouts...). Concatenated\n# after the NEJEN defaults and theme colors, so values here win. [criteria]\n# sections are not allowed here. Never touched by NEJEN updates.")

	makoContent := "# " + genMark + " - DO NOT EDIT. Regenerated from:\n#   $NEJEN_PATH/config/mako/config + ~/.local/state/nejen/theme/mako.ini\n#   + ~/.config/nejen/mako-overrides + $NEJEN_PATH/config/mako/sections\n"
	if b, err := os.ReadFile(filepath.Join(nejenPath, "config", "mako", "config")); err == nil {
		makoContent += string(b)
	}
	if b, err := os.ReadFile(filepath.Join(stateDir, "theme", "mako.ini")); err == nil {
		makoContent += "\n" + string(b)
	}
	if b, err := os.ReadFile(filepath.Join(configDir, "nejen", "mako-overrides")); err == nil {
		makoContent += "\n" + string(b)
	}
	if b, err := os.ReadFile(filepath.Join(nejenPath, "config", "mako", "sections")); err == nil {
		makoContent += "\n" + string(b)
	}
	writeGen(filepath.Join(configDir, "mako", "config"), makoContent)

	linkTo(filepath.Join(nejenPath, "config", "fastfetch"), filepath.Join(configDir, "fastfetch"))
	linkTo(filepath.Join(nejenPath, "config", "walker"), filepath.Join(configDir, "walker"))
	linkTo(filepath.Join(nejenPath, "config", "nvim"), filepath.Join(configDir, "nvim"))
	linkTo(filepath.Join(nejenPath, "config", "uwsm"), filepath.Join(configDir, "uwsm"))

	os.MkdirAll(filepath.Join(configDir, "elephant", "menus"), 0755)
	if menus, err := filepath.Glob(filepath.Join(nejenPath, "config", "elephant", "menus", "*.lua")); err == nil {
		for _, m := range menus {
			linkTo(m, filepath.Join(configDir, "elephant", "menus", filepath.Base(m)))
		}
	}

	os.MkdirAll(filepath.Join(configDir, "systemd", "user"), 0755)
	if units, err := filepath.Glob(filepath.Join(nejenPath, "config", "systemd", "user", "*")); err == nil {
		for _, u := range units {
			linkTo(u, filepath.Join(configDir, "systemd", "user", filepath.Base(u)))
		}
	}

	zenDesktop := filepath.Join(nejenPath, "templates", "zen.desktop")
	if _, err := os.Stat(zenDesktop); err == nil {
		os.MkdirAll(filepath.Join(home, ".local", "share", "applications"), 0755)
		linkTo(zenDesktop, filepath.Join(home, ".local", "share", "applications", "zen.desktop"))
	}

	installLog("Wiring shell + compose defaults...")
	ensureOverride(filepath.Join(configDir, "nejen", "bash-overrides"), "# Your personal bash setup (aliases, functions, prompt tweaks...). Sourced at\n# the end of NEJEN's bash rc, so everything here wins. Never touched by NEJEN\n# updates.")

	bashrc := filepath.Join(home, ".bashrc")
	bashrcContent, _ := os.ReadFile(bashrc)
	if !strings.Contains(string(bashrcContent), "nejen/config/bash/rc") {
		f, err := os.OpenFile(bashrc, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
		if err == nil {
			f.WriteString(fmt.Sprintf("\n# NEJEN shell defaults (%s)\nsource \"%s/config/bash/rc\"\n", genMark, nejenPath))
			f.Close()
			installLog("Added NEJEN source line to ~/.bashrc")
		}
	}

	xcompose := filepath.Join(home, ".XCompose")
	xcomposeContent, err := os.ReadFile(xcompose)
	if err != nil { // not exists
		os.WriteFile(xcompose, []byte(fmt.Sprintf("# %s\ninclude \"%%H/.local/share/nejen/config/xcompose\"\n", genMark)), 0644)
	} else if !strings.Contains(string(xcomposeContent), "nejen/config/xcompose") {
		installWarn("~/.XCompose exists without the NEJEN include - left untouched.")
	}

	installLog("Enabling user systemd services...")
	exec.Command("systemctl", "--user", "daemon-reload").Run()
	if err := exec.Command(filepath.Join(nejenPath, "bin", "nejen"), "battery", "present").Run(); err == nil {
		exec.Command("systemctl", "--user", "enable", "--now", "nejen-battery-monitor.timer").Run()
	}

	installLog("Done. Make sure ~/.local/bin is on PATH, then start a new shell or Hyprland session.")
}
